# Generated by Django 5.0 on 2024-06-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PAGINA_WEB', '0002_genero_alumno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Usuario',
        ),
    ]
