# Generated by Django 5.0.6 on 2024-06-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PAGINA_WEB', '0003_rename_alumno_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_genero',
        ),
        migrations.DeleteModel(
            name='MiModelo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rut',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
