# Generated by Django 5.0.6 on 2024-06-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGINA_WEB', '0004_remove_usuario_id_genero_delete_mimodelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('Titulo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
    ]
