# Generated by Django 5.0.6 on 2024-07-03 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGINA_WEB', '0007_rename_titulo_manga_titulo_alter_capitulo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
